<?php

namespace AppBundle\Repository;

/**
 * AcademiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademiaRepository extends \Doctrine\ORM\EntityRepository
{
}
