<?php

namespace AppBundle\Repository;

/**
 * LanguagesHobbiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguagesHobbiesRepository extends \Doctrine\ORM\EntityRepository
{
}
