<?php

namespace AppBundle\Repository;

/**
 * ProfExpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfExpRepository extends \Doctrine\ORM\EntityRepository
{
}
