<?php

namespace AppBundle\Repository;

/**
 * TechtagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechtagRepository extends \Doctrine\ORM\EntityRepository
{
}
